metric: COCO
num_classes: 10

TrainDataset:
  name: COCODataSet
  image_dir: VisDrone2019-DET-train
  anno_path: annotations/instances_train2017.json
  dataset_dir: ../data/visdrone
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: VisDrone2019-DET-val
  anno_path: annotations/instances_val2017.json
  dataset_dir: ../data/visdrone
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: test_dev.json # also support txt (like VOC's label_list.txt)
  dataset_dir: ../data/visdrone # if set, anno_path will be 'dataset_dir/anno_path'
