metric: COCO
num_classes: 5

TrainDataset:
  name: COCODataSet
  image_dir: train2017
  anno_path: annotations/instances_train2017.json
  dataset_dir: ../data/vehicle
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val2017
  anno_path: annotations/instances_val2017.json
  dataset_dir: ../data/vehicle
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: ..\data\visdrone # also support txt (like VOC's label_list.txt)
  dataset_dir: ./data/vehicle # if set, anno_path will be 'dataset_dir/anno_path'
