metric: VOC
map_type: integral
num_classes: 4

TrainDataset:
  name: VOCDataSet
  dataset_dir: ../data/DatasetVocSASU_ForIcarM2023
  anno_path: train.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: ../data/DatasetVocSASU_ForIcarM2023
  anno_path: val.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: ../data/DatasetVocSASU_ForIcarM2023/trainval.txt
